// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5dVcalzWfmC3unCpPngtZFrly2_KUQAQ',
    appId: '1:757106583943:android:a1a7b007a041cb1c9b4b22',
    messagingSenderId: '757106583943',
    projectId: 'jesus-new-app',
    storageBucket: 'jesus-new-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfozEVMzLdsIpn8EuP49SAh-sccEjvWk',
    appId: '1:757106583943:ios:f0d400faf633aae79b4b22',
    messagingSenderId: '757106583943',
    projectId: 'jesus-new-app',
    storageBucket: 'jesus-new-app.firebasestorage.app',
    iosBundleId: 'com.cassarly.jesusnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsopdUraHnA8AQArGIDYN3e1MGtSugT-Q',
    appId: '1:666939462503:ios:f35e75bd7858235eef15c2',
    messagingSenderId: '666939462503',
    projectId: 'jesusnew-5a1e3',
    storageBucket: 'jesusnew-5a1e3.firebasestorage.app',
    iosBundleId: 'com.example.clientapp',
  );
}